version: "3.9"

services:

  fastapi:
    container_name: api
    build:
      dockerfile: ./config/dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./config/.env
    volumes:
      - ./source:/app/source